//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantDisease.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObservationFactor
    {
        public int Id { get; set; }
        public int FactorId { get; set; }
        public decimal FactorValue { get; set; }
        public int ObservationId { get; set; }
    
        public virtual Factor Factor { get; set; }
        public virtual Observation Observation { get; set; }
    }
}
