//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantDisease.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Observation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Observation()
        {
            this.ObservationFactors = new HashSet<ObservationFactor>();
        }
    
        public int Id { get; set; }
        public System.DateTime ObservationDate { get; set; }
        public int PlantDiseaseId { get; set; }
        public bool InfectionClassification { get; set; }
        public decimal InfectionValue { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Name { get; set; }
    
        public virtual PlantDiseaseJunc PlantDiseaseJunc { get; set; }
        public virtual Plant Plant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObservationFactor> ObservationFactors { get; set; }
    }
}
