//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantDisease.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantDiseaseJunc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlantDiseaseJunc()
        {
            this.Observations = new HashSet<Observation>();
            this.PlantDiseaseFactors = new HashSet<PlantDiseaseFactor>();
        }
    
        public int Id { get; set; }
        public int PlantId { get; set; }
        public int DiseaseId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual Disease Disease { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Observation> Observations { get; set; }
        public virtual Plant Plant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlantDiseaseFactor> PlantDiseaseFactors { get; set; }
    }
}
